language: r

services:
    - rabbitmq

apt_packages:
    - librabbitmq-dev

matrix:
    include:
        - name: "Trusty"
          dist: trusty
        - name: "Xenial"
          dist: xenial
          before_install:
              - apt-get install rabbitmq-server
        - name: "OSX"
          os: osx
          brew_packages: rabbitmq-c
