# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

amqp_connect <- function(host, port) {
    .Call('_rabbitr_connect', PACKAGE = 'rabbitr', host, port)
}

amqp_channel_open <- function(xptr, channel) {
    invisible(.Call('_rabbitr_channel_open', PACKAGE = 'rabbitr', xptr, channel))
}

amqp_queue_declare <- function(xptr, channel, queue, passive, durable, exclusive, auto_delete) {
    invisible(.Call('_rabbitr_queue_declare', PACKAGE = 'rabbitr', xptr, channel, queue, passive, durable, exclusive, auto_delete))
}

amqp_queue_delete <- function(xptr, channel, queue, if_unused, if_empty) {
    invisible(.Call('_rabbitr_queue_delete', PACKAGE = 'rabbitr', xptr, channel, queue, if_unused, if_empty))
}

amqp_basic_get <- function(xptr, channel, queue) {
    .Call('_rabbitr_basic_get', PACKAGE = 'rabbitr', xptr, channel, queue)
}

