# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

amqp_connect <- function(host, port) {
    .Call('_rabbitr_connect', PACKAGE = 'rabbitr', host, port)
}

amqp_channel_open <- function(xptr, channel) {
    invisible(.Call('_rabbitr_channel_open', PACKAGE = 'rabbitr', xptr, channel))
}

amqp_queue_declare <- function(xptr) {
    invisible(.Call('_rabbitr_queue_declare', PACKAGE = 'rabbitr', xptr))
}

amqp_consume <- function(xptr) {
    invisible(.Call('_rabbitr_consume', PACKAGE = 'rabbitr', xptr))
}

