# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

amqp_connect <- function(host, port, username, password) {
    .Call('_rabbitr_connect', PACKAGE = 'rabbitr', host, port, username, password)
}

amqp_channel_open <- function(xptr, channel) {
    invisible(.Call('_rabbitr_channel_open', PACKAGE = 'rabbitr', xptr, channel))
}

amqp_queue_declare <- function(xptr, channel, queue, passive, durable, exclusive, auto_delete) {
    invisible(.Call('_rabbitr_queue_declare', PACKAGE = 'rabbitr', xptr, channel, queue, passive, durable, exclusive, auto_delete))
}

amqp_queue_bind <- function(xptr, channel, queue, exchange, routing_key) {
    invisible(.Call('_rabbitr_queue_bind', PACKAGE = 'rabbitr', xptr, channel, queue, exchange, routing_key))
}

amqp_queue_unbind <- function(xptr, channel, queue, exchange, routing_key) {
    invisible(.Call('_rabbitr_queue_unbind', PACKAGE = 'rabbitr', xptr, channel, queue, exchange, routing_key))
}

amqp_queue_purge <- function(xptr, channel, queue) {
    invisible(.Call('_rabbitr_queue_purge', PACKAGE = 'rabbitr', xptr, channel, queue))
}

amqp_queue_delete <- function(xptr, channel, queue, if_unused, if_empty) {
    invisible(.Call('_rabbitr_queue_delete', PACKAGE = 'rabbitr', xptr, channel, queue, if_unused, if_empty))
}

amqp_listen <- function(xptr, callback, timeout = NULL) {
    invisible(.Call('_rabbitr_listen', PACKAGE = 'rabbitr', xptr, callback, timeout))
}

amqp_basic_get <- function(xptr, channel, queue, no_ack) {
    .Call('_rabbitr_basic_get', PACKAGE = 'rabbitr', xptr, channel, queue, no_ack)
}

amqp_basic_cancel <- function(xptr, channel, consumer_tag) {
    invisible(.Call('_rabbitr_basic_cancel', PACKAGE = 'rabbitr', xptr, channel, consumer_tag))
}

amqp_basic_publish <- function(xptr, channel, exchange, routing_key, mandatory, immediate, body) {
    invisible(.Call('_rabbitr_basic_publish', PACKAGE = 'rabbitr', xptr, channel, exchange, routing_key, mandatory, immediate, body))
}

amqp_basic_consume <- function(xptr, channel, queue, consumer_tag, no_ack, exclusive) {
    invisible(.Call('_rabbitr_basic_consume', PACKAGE = 'rabbitr', xptr, channel, queue, consumer_tag, no_ack, exclusive))
}

